In [172]:

from sklearn import svm, metrics
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

data = pd.read_csv("processed.hungarian.data", header=None, names=['age','sex',"cp", "trestbps", "chol", "fbs", 
                                                                   "restecg", "thalach", "exang", "oldpeak", "slope", 
                                                                   "ca" , "thal", "num"])

data.head()



age  sex  cp trestbps chol fbs restecg thalach exang  oldpeak slope ca  \
0   28    1   2      130  132   0       2     185     0      0.0     ?  ?   
1   29    1   2      120  243   0       0     160     0      0.0     ?  ?   
2   29    1   2      140    ?   0       0     170     0      0.0     ?  ?   
3   30    0   1      170  237   0       1     170     0      0.0     ?  ?   
4   31    0   2      100  219   0       1     150     0      0.0     ?  ?   

  thal  num  
0    ?    0  
1    ?    0  
2    ?    0  
3    6    0  
4    ?    0

In [173]:
X_features = data.drop(columns=['thal','ca', 'slope','chol', 'fbs'], axis=1)
X_features.head(5)

index_list = []

for index1,line in enumerate(X_features.values):
    for index2, value in enumerate(line):
        if value == '?':
            index_list.append(index1)

print(index_list)
X_features = X_features.drop(index=index_list, axis=1)
X_features.head()

[90, 90, 90, 268]


age  sex  cp trestbps restecg thalach exang  oldpeak  num
0   28    1   2      130       2     185     0      0.0    0
1   29    1   2      120       0     160     0      0.0    0
2   29    1   2      140       0     170     0      0.0    0
3   30    0   1      170       1     170     0      0.0    0
4   31    0   2      100       1     150     0      0.0    0

In [174]:
Y_Target = X_features['num']

Y_Target.head()





0    0
1    0
2    0
3    0
4    0
Name: num, dtype: int64

In [175]:
X_train, X_test, Y_train, Y_test = train_test_split(X_features.as_matrix(), Y_Target.as_matrix(), test_size=0.1, train_size=0.9, shuffle=True)



classifier = svm.SVC(gamma=0.001)
classifier.fit(X_train,Y_train)

from sklearn.model_selection import cross_val_score

scores = cross_val_score(classifier, X_features, Y_Target, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))


Accuracy: 0.67 (+/- 0.12)


d:\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [176]:
prediction = classifier.predict(X_test)
Y_test
# print(prediction)
# for index, (prediction, Y_test) in enumerate(list(zip(prediction,Y_test))):
#     if prediction == Y_test:
#         print(f"Success {index}: Prediction:{prediction} Result:{Y_test}")
#     else:
#         print(f"Failure {index}: Prediction:{prediction} Result:{Y_test}")


array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1], dtype=int64)

In [177]:

print(metrics.classification_report(prediction, Y_test))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(prediction, Y_test))



              precision    recall  f1-score   support

           0       0.89      0.63      0.74        27
           1       0.09      0.33      0.14         3

    accuracy                           0.60        30
   macro avg       0.49      0.48      0.44        30
weighted avg       0.81      0.60      0.68        30

Confusion matrix:
[[17 10]
 [ 2  1]]


This time I will standardise the X and Y data, to see if performance increases

In [178]:
data = pd.read_csv("processed.hungarian.data", header=None, names=['age','sex',"cp", "trestbps", "chol", "fbs", 
                                                                   "restecg", "thalach", "exang", "oldpeak", "slope", 
                                                                   "ca" , "thal", "num"])

data.head()

age  sex  cp trestbps chol fbs restecg thalach exang  oldpeak slope ca  \
0   28    1   2      130  132   0       2     185     0      0.0     ?  ?   
1   29    1   2      120  243   0       0     160     0      0.0     ?  ?   
2   29    1   2      140    ?   0       0     170     0      0.0     ?  ?   
3   30    0   1      170  237   0       1     170     0      0.0     ?  ?   
4   31    0   2      100  219   0       1     150     0      0.0     ?  ?   

  thal  num  
0    ?    0  
1    ?    0  
2    ?    0  
3    6    0  
4    ?    0

In [179]:
from sklearn import preprocessing

X_features = data.drop(columns=['thal','ca', 'slope','chol', 'fbs'], axis=1)
X_features.head(5)

index_list = []

for index1,line in enumerate(X_features.values):
    for index2, value in enumerate(line):
        if value == '?':
            index_list.append(index1)


X_features = X_features.drop(index=index_list, axis=1)
Y_Target = X_features['num']




In [180]:
X_features = preprocessing.scale(X_features)



In [181]:
# X_features = preprocessing.scale(X_features)
min_max_scaler = preprocessing.MinMaxScaler()
X_features = min_max_scaler.fit_transform(X_features)

X_features = pd.DataFrame(X_features)
X_features.tail(10)

0    1         2         3    4         5    6    7    8
282  0.552632  1.0  1.000000  0.333333  0.0  0.129630  1.0  0.0  1.0
283  0.552632  1.0  1.000000  0.537037  0.0  0.370370  0.0  0.4  1.0
284  0.578947  1.0  1.000000  0.444444  0.5  0.537037  1.0  1.0  1.0
285  0.578947  1.0  1.000000  0.444444  0.5  0.398148  1.0  0.5  1.0
286  0.631579  1.0  1.000000  0.444444  0.0  0.481481  1.0  0.4  1.0
287  0.631579  1.0  1.000000  0.629630  0.0  0.111111  1.0  0.5  1.0
288  0.684211  0.0  0.666667  0.351852  0.5  0.166667  1.0  0.0  1.0
289  0.736842  1.0  1.000000  0.583333  0.0  0.629630  1.0  0.6  1.0
290  0.789474  0.0  0.333333  0.814815  0.0  0.259259  1.0  0.2  1.0
291  0.973684  1.0  1.000000  0.351852  0.5  0.305556  1.0  0.2  1.0

In [182]:
# Y_Target = preprocessing.scale(Y_Target)
# Y_Target = pd.DataFrame(Y_Target)



# Y_Target.tail(10)



In [183]:
from sklearn import utils

X_train, X_test, Y_train, Y_test = train_test_split(X_features, Y_Target, test_size=0.1, train_size=0.9, shuffle=True)


In [184]:

classifier = svm.SVC(gamma=0.001)
classifier.fit(X_train,Y_train)


from sklearn.model_selection import cross_val_score

scores = cross_val_score(classifier, X_features, Y_Target, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.64 (+/- 0.01)


In [185]:

prediction = classifier.predict(X_test)

# print(prediction)
# for index, (prediction, Y_test) in enumerate(list(zip(prediction,Y_test))):
#     if prediction == Y_test:
#         print(f"Success {index}: Prediction:{prediction} Result:{Y_test}")
#     else:
#         print(f"Failure {index}: Prediction:{prediction} Result:{Y_test}")
print(metrics.classification_report(prediction, Y_test))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(prediction, Y_test))




              precision    recall  f1-score   support

           0       1.00      0.53      0.70        30
           1       0.00      0.00      0.00         0

    accuracy                           0.53        30
   macro avg       0.50      0.27      0.35        30
weighted avg       1.00      0.53      0.70        30

Confusion matrix:
[[16 14]
 [ 0  0]]


d:\python\python37-32\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


preprocessing the X data has proven in this instance to reduce accuracy by at least 10%. 


